Tarifim.WebUI/Areas/Admin/Controllers/DashboardController.cs
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using System.Data;

namespace Tarifim.WebUI.Areas.Admin.Controllers
{
    [Area("Admin")]
    //[Authorize(Roles = "admin")]

    public class DashboardController : Controller
    {
        
        public IActionResult Index()
        {
            return View();
        }


    }
}

Tarifim.WebUI/Controllers/AuthController.cs
using Tarifim.Business.Dtos;
using Tarifim.Business.Services;
using Tarifim.WebUI.Models;
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Authentication.Cookies;
using Microsoft.AspNetCore.Mvc;
using System.Security.Claims;

namespace Tarifim.WebUI.Controllers
{
    public class AuthController : Controller
    {
        private readonly IUserService _userService;
        public AuthController(IUserService userService)
        {
            _userService = userService;
        }

        [HttpGet]
       
        public IActionResult Register()
        {
            return View();
        }

        [HttpPost]
        public IActionResult Register(RegisterViewModel formData)
        {
            if (!ModelState.IsValid)
            {
                return View(formData);
            }

            var userDto = new UserDto()
            {
                Name = formData.Name.Trim(),
                SurName = formData.SurName.Trim(),
                Email = formData.Email.Trim(),
                Password = formData.Password.Trim(),
            };

            var response = _userService.addUser(userDto);

            if (response.IsSucceed)
            {
                return RedirectToAction("Index","Login");
            }
            else
            {
                ViewBag.ErrorMessage = response.Message;
                return View(formData);
            }
        }

        public async Task<IActionResult> Login(LoginViewModel formData)
        {
            var loginDto = new LoginDto()
            {
                Email = formData.Email.Trim(),
                Password = formData.Password.Trim(),
            };

           var user=_userService.login(loginDto);

            if (user is null)
            {
                TempData["Message"] = "Email vaya şifre hatalı girdiniz.";
                
                return RedirectToAction("Index" , "Login");
                
            }
            

            var claims = new List<Claim>();
            
                claims.Add(new Claim("id", user.Id.ToString()));
                claims.Add(new Claim("name", user.Name));
                claims.Add(new Claim("surname", user.SurName));
                claims.Add(new Claim("email", user.Email));
                claims.Add(new Claim("usertype", user.UserType.ToString()));
                claims.Add(new Claim(ClaimTypes.Role, user.UserType.ToString()));

            var claimIdentity = new ClaimsIdentity(claims, CookieAuthenticationDefaults.AuthenticationScheme);

            var autProperties = new AuthenticationProperties
            {
                AllowRefresh = true,
                ExpiresUtc = new DateTimeOffset(DateTime.Now.AddHours(12))
            };

            await HttpContext.SignInAsync(CookieAuthenticationDefaults.AuthenticationScheme, new ClaimsPrincipal(claimIdentity), autProperties);

            return RedirectToAction("index", "Home");

           
        }


        public async Task<IActionResult> Logout()
        {
            await HttpContext.SignOutAsync();
            return RedirectToAction("index", "home");
        }


    }
}

Tarifim.WebUI/Areas/Admin/Views/Shared/_Layout.cshtml
@using Tarifim.WebUI.Extensions;
<html>
<head>

    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-GLhlTQ8iRABdZLl6O3oVMWSktQOp6b7In1Zl3/Jr59b6EGGoI1aFkw7cmDA6j6gD" crossorigin="anonymous">

    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.10.3/font/bootstrap-icons.css">



  

    <style>
        .dashbutton {
            display: inline-block;
            border-radius: 4px;
            background-color: #f4511e;
            border: none;
            color: #FFFFFF;
            text-align: center;
            font-size: 28px;
            padding: 20px;
            width: 200px;
            transition: all 0.5s;
            cursor: pointer;
            margin: 5px;
        }

            .dashbutton span {
                cursor: pointer;
                display: inline-block;
                position: relative;
                transition: 0.5s;
            }

                .dashbutton span:after {
                    content: '\00bb';
                    position: absolute;
                    opacity: 0;
                    top: 0;
                    right: -20px;
                    transition: 0.5s;
                }

            .dashbutton:hover span {
                padding-right: 25px;
            }

                .dashbutton:hover span:after {
                    opacity: 1;
                    right: 0;
                }

        .homebutton {
            display: inline-block;
            padding: 15px 25px;
            font-size: 24px;
            cursor: pointer;
            text-align: center;
            text-decoration: none;
            outline: none;
            color: #fff;
            background-color: #f4511e;
            border: none;
            border-radius: 15px;
            box-shadow: 0 9px #999;
        }

            .homebutton:hover {
                background-color: #3e8e41
            }

            .homebutton:active {
                background-color: #3e8e41;
                box-shadow: 0 5px #666;
                transform: translateY(4px);
            }
    </style>


</head>
<body>

    <div class="container">
        <header class="d-flex flex-wrap align-items-center justify-content-center justify-content-md-between py-3 mb-4 border-bottom">
            <a href="/" class="d-flex align-items-center col-md-3 mb-2 mb-md-0 text-dark text-decoration-none">
                <svg class="bi me-2" width="40" height="32" role="img" aria-label="Bootstrap"><use xlink:href="#bootstrap"></use></svg>
            </a>

            <ul class="nav col-12 col-md-auto mb-2 justify-content-center mb-md-0">
                <li><a asp-area="Admin" asp-controller="Dashboard" asp-action="Index" class="nav-link px-2 link-secondary fs-2 fw-bold fst-italic">Tarifim | Yönetim Paneli</a></li>
            </ul>
            <ul class="nav col-12 col-md-auto mb-2 justify-content-center mb-md-0">
                <li><a asp-area="" asp-controller="Auth" asp-action="Logout" class="btn btn-outline-danger">Çıkış</a></li>
            </ul>


        </header>

    </div>

    <div class="text-white" style="position:fixed;margin-left:85%;margin-top:10px;margin-bottom:10px;">
        <a asp-area="" asp-controller="home" asp-action="index" class="homebutton" style="float:right;margin-right:50px;"><i class="bi bi-house-heart-fill"></i></a>
    </div>


    @RenderBody()

</body>
</html>