Tarifim.WebUI/Areas/Admin/Models/FoodListViewModel.cs
using System.ComponentModel.DataAnnotations;
using System.Xml.Linq;

namespace Tarifim.WebUI.Areas.Admin.Models
{
    public class FoodListViewModel
    {
        public int Id { get; set; }

        
        public string Name { get; set; }

        
        public string Content { get; set; }

       
        public string Description { get; set; }

        
        public string CategoryName { get; set; }

       
        public string FoodImage { get; set; }
    }
}

Tarifim.WebUI/Controllers/FoodListController.cs
using Microsoft.AspNetCore.Mvc;
using Tarifim.Business.Services;
using Tarifim.WebUI.Extensions;
using Tarifim.WebUI.Models;

namespace Tarifim.WebUI.Controllers
{
    public class FoodListController : Controller
    {
        private readonly IFoodService _foodService;

        public FoodListController(IFoodService foodService)
        {

            _foodService = foodService;
        }
        public IActionResult List(int? id)
        {
            var foodDto = _foodService.GetFoods(id);

            if (!User.IsLogged())
            {
                return RedirectToAction("Index", "Login");
            }

            var viewModel = foodDto.Select(x => new FoodListModel
            {
                Id = x.Id,
                Name = x.Name,
                CategoryName = x.CategoryName,
                ImagePath = x.FoodImage
            }).ToList();

            return View(viewModel);


        }


        public IActionResult Detail(int id)
        {
            var foodDetailDto = _foodService.GetFoodDetail(id);

            var viewModel = new FoodDetailModel()
            {
                Name = foodDetailDto.Name,
                Content = foodDetailDto.Content,
                Description = foodDetailDto.Description,
                ImagePath = foodDetailDto.ImagePath,
                CategoryName = foodDetailDto.CategoryName,
                ModifiedDate = foodDetailDto.ModifiedDate,
            };

            return View(viewModel);
        }
    }
}

Tarifim.WebUI/Views/FoodList/Detail.cshtml
@model FoodDetailModel

<div class="container">
    <div class="row">
        <div class="col-lg-12">
            <div class="card">
                <div class="card-head">
                    <div style="text-align:center;justify-items:center;;margin-top:10px;">

                        @if (string.IsNullOrWhiteSpace(Model.ImagePath))
                        {
                            <img class="mx-auto d-block" style="width:300px; height:300px;margin:auto;border-radius:50px;" src="~/images/noPhoto.png" />
                        }
                        else
                        {
                            <img class="mx-auto d-block" style="width:300px; height:300px;margin:auto;border-radius:50px;" src="~/images/foods/@Model.ImagePath" />
                        }
                    </div>
                </div>
                <div class="card-body">
                    <div>


                        <div style="text-align: center;">
                            <h2>@Model.Name</h2>
                        </div>

                        <hr />

                        <div style="text-align: center;">
                            @Model.Content
                        </div>

                        <hr />

                        <div style="text-align: center;">
                            @Model.Description
                        </div>

                        <hr />

                        <div style="text-align: center;">
                            @Model.CategoryName
                        </div>

                        <hr />

                        <div style="text-align: center;">

                            @if (!string.IsNullOrWhiteSpace(@Model.ModifiedDate.ToString()))
                            {
                                <p>
                                    <small class="text-muted">
                                        Son Güncelleme :
                                        @Model.ModifiedDate.Value.Day gün önce
                                    </small>
                                </p>
                            }
                            else
                            {
                                <p>
                                    <small class="text-muted"> Bu ürün güncellenmemiştir! </small>
                                </p>
                            }
                        </div>
                    </div>
                </div>
                
            </div>
        </div>

    </div>
</div>

Tarifim.WebUI/Views/FoodList/List.cshtml
@model List<FoodListModel>


<div class="container">
    <div class="container mt-3">
        <h2 style="color:orangered" class="container">
            @if (Model.Count == 0)
            {
                <div class="container">
                    <div class="row">
                        <div class="alert alert-danger">Henüz bir yemek eklenmemiştir!!!</div>
                    </div>
                </div>
            }
        </h2>
    </div>
</div>



<div class="container">

    <table class="table table-striped ">

        <thead>

            <tr>
                <th style="width:400px">Yemek Resim</th>
                <th style="width:400px">Yemek Adı</th>
                <th style="width:400px">Kategori</th>
            </tr>

        </thead>

        @foreach (var foods in Model)
        {

            <tbody>
                <tr>
                    <td>
                        @if (string.IsNullOrWhiteSpace(foods.ImagePath))
                        {
                            <img src="~/images/noPhoto.png" style="width:120px; height:120px;border-radius:50px;" />
                        }
                        else
                        {
                            <img src="~/images/foods/@foods.ImagePath" alt="@foods.Name" style="width:120px; height:120px;border-radius:50px;" />
                        }
                    </td>

                    <td style="justify-items:center">@foods.Name</td>
                    <td style="justify-items:center">@foods.CategoryName</td>

                    <td>
                        <a asp-controller="FoodList" asp-action="Detail" asp-route-id="@foods.Id" class="btn btn-sm btn-primary"><i class="bi bi-pencil-square"></i>Ayrıntısı</a>

                    </td>

                </tr>



            </tbody>
        }
    </table>

</div>