Tarifim.WebUI/Areas/Admin/Controllers/DashboardController.cs
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using System.Data;

namespace Tarifim.WebUI.Areas.Admin.Controllers
{
    [Area("Admin")]
    //[Authorize(Roles = "admin")]

    public class DashboardController : Controller
    {
        
        public IActionResult Index()
        {
            return View();
        }


    }
}

Tarifim.WebUI/Areas/Admin/Controllers/FoodController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using System.Data;
using Tarifim.Business.Dtos;
using Tarifim.Business.Services;
using Tarifim.WebUI.Areas.Admin.Models;

namespace Tarifim.WebUI.Areas.Admin.Controllers
{
    [Area("Admin")]
   // [Authorize(Roles = "admin")]
    public class FoodController : Controller
    {
        private readonly IFoodService _foodService;
        private readonly ICategoryService _categoryService;
        private readonly IWebHostEnvironment _webHostEnvironment;

        public FoodController(IFoodService foodService,ICategoryService categoryService,
            IWebHostEnvironment webHostEnvironment)
        {
            _foodService = foodService;
            _categoryService = categoryService;
            _webHostEnvironment = webHostEnvironment;
        }

       
        public IActionResult List()
        {
            var foodDtos=_foodService.GetFoods(null);

            var viewModel = foodDtos.Select(x => new FoodListViewModel
            {
                Id = x.Id,
                Name = x.Name,
                Content = x.Content,
                Description = x.Description,
                CategoryName = x.CategoryName,
                FoodImage = x.FoodImage,
            }).ToList();

            return View(viewModel);
        }
        [HttpGet]
        public IActionResult NewFood() 
        {
            ViewBag.Categories=_categoryService.GetCategories();
            return View("Form",new FoodFormViewModel());
        }

        public IActionResult AddFood(FoodFormViewModel formData)
        {
            if (!ModelState.IsValid)
            {
                ViewBag.Categories = _categoryService.GetCategories();
                return View("Form", formData);
            }
            var fileName = "";

            if (formData.File != null)
            {


                var allowedFileContentTypes = new string[] { "image/jpeg", "image/jpg", "image/png", "image/jfif" };

                var allowedFileExtensions = new string[] { ".jpg", ".jpeg", ".png", ".jfif" };


                var fileContentType = formData.File.ContentType;
                var fileNameWithoutExtension = Path.GetFileNameWithoutExtension(formData.File.FileName);
                var fileExtension = Path.GetExtension(formData.File.FileName);

                

                if (!allowedFileContentTypes.Contains(fileContentType) ||
                        !allowedFileExtensions.Contains(fileExtension))
                {
                    ViewBag.FileError = "Lütfen jpg , jpeg , png veya jfif tipinde geçerli bir dosya yükleyiniz.";
                    ViewBag.Categories = _categoryService.GetCategories();
                    return View("form", formData);
                }

                fileName = fileNameWithoutExtension + "-" + Guid.NewGuid() + fileExtension;

                var folderPath = Path.Combine("images", "foods");
                var wwwRootFolderPath = Path.Combine(_webHostEnvironment.WebRootPath, folderPath);
                var wwwRootFilePath = Path.Combine(wwwRootFolderPath, fileName);

                Directory.CreateDirectory(wwwRootFolderPath);

                using (var fileStream = new FileStream(wwwRootFilePath, FileMode.Create))
                {
                    formData.File.CopyTo(fileStream);
                }
               
            }

            if (formData.Id == 0)
            {
                var foodDto = new FoodDto()
                {
                    Id = formData.Id,
                    Name = formData.Name,
                    Content = formData.Content,
                    Description = formData.Description,
                    CategoryId = formData.CategoryId,
                    FoodImage = fileName
                };

                var response = _foodService.AddFood(foodDto);

                if (response.IsSucceed)
                {
                    return RedirectToAction("List");
                }
                else
                {
                    ViewBag.ErrorMessage = response.Message;
                    ViewBag.Categories = _categoryService.GetCategories();
                    return View("Form", formData);
                }
            }
            else
            {
                var foodDto = new FoodDto()
                {
                    Id = formData.Id,
                    Name = formData.Name,
                    Content = formData.Content,
                    Description = formData.Description,
                    CategoryId = formData.CategoryId,
                    
                };
                if (formData.File != null)
                {
                    foodDto.FoodImage = fileName;
                }

                _foodService.UpdateFood(foodDto);
            }

            return RedirectToAction("List");
        }
        public IActionResult UpdateFood(int id)
        {
            var foodDto=_foodService.GetFoodId(id);

            var viewModel = new FoodFormViewModel()
            {
                Id = foodDto.Id,
                Name = foodDto.Name,
                Content = foodDto.Content,
                Description = foodDto.Description,
                CategoryId = foodDto.CategoryId,

            };
            ViewBag.Categories=_categoryService.GetCategories();
            ViewBag.FoodImage = foodDto.FoodImage;

            return View("Form", viewModel);
        }
        public IActionResult DeleteFood(int id) 
        {
            _foodService.DeleteFood(id);
            return RedirectToAction("List");
        }
    }
}

Tarifim.WebUI/Areas/Admin/Views/Food/Form.cshtml
@model FoodFormViewModel

<div class="container" style="padding-top:40px">
    <div class="row">
        <div class="col-md-8 offset-2">

            <div class="card" style="border:solid 2px">
                <div class="card-header fw-bold fs-5">
                    @(Model.Id == 0 ? "Yemek Ekleme Formu" : "Yemek Düzenleme Formu")
                </div>
                <div class="card-body">
                    <form method="post" asp-area="Admin" asp-controller="Food" asp-action="AddFood" enctype="multipart/form-data">
                       

                        @if (!string.IsNullOrWhiteSpace(ViewBag.ErrorMessage))
                        {
                            <div class="alert alert-danger">
                                @ViewBag.ErrorMessage
                            </div>
                        }

                        <input asp-for="Id" type="hidden" />

                        <div class="form-group mb-2">
                            <label class="required" asp-for="Name"></label>
                            <input asp-for="Name" class="form-control" type="text" />
                            <span class="text-danger fw-bold" asp-validation-for="Name"></span>

                        </div>

                        <div class="form-group mb-2">
                            <label  asp-for="Content"></label>
                            <textarea asp-for="Content" class="form-control" rows="3"></textarea>   
                            <span class="text-danger fw-bold" asp-validation-for="Content"></span>

                        </div>

                        <div class="form-group">
                            <label asp-for="Description"></label>
                            <textarea class="form-control" type="text" asp-for="Description" rows="2" cols="50"></textarea>
                            <span class="text-danger fw-bold" asp-validation-for="Description"></span>
                        </div>

                        <div class="form-group">
                            <label class="required" asp-for="CategoryId"></label>
                            <select asp-items="@(new SelectList(ViewBag.Categories , "Id" , "Name"))" class="form-control" type="text" asp-for="CategoryId">
                           <option selected >Seçiniz</option>
                            </select>
                            <span class="text-danger fw-bold" asp-validation-for="CategoryId"></span>
                        </div>

                        <div class="form-group">
                            <label asp-for="File"></label>

                            @if (Model.Id != 0) 
                            {
                                @if (!string.IsNullOrWhiteSpace(@ViewBag.FoodImage))
                                {
                                    <div>
                                        <img src="~/images/foods/@ViewBag.FoodImage" style="width:200px; height:200px;border-radius:50px;" />
                                    </div>
                                }
                                else
                                {
                                    <div>
                                        <img src="~/images/noPhoto.png" style="width:200px; height:200px;border-radius:50px;" />
                                    </div>
                                }
                            }


                            <input asp-for="File" type="file" class="form-control mt-2" />
                        </div>




                        <button type="submit" class="btn btn-success mt-3 float-end">@(Model.Id == 0 ? "Kaydet" : "Güncelle")</button>
                        <a asp-controller="Dashboard" asp-action="Index" class="btn btn-sm btn-primary mt-3" style="float:right">Geri Dön</a>

                    </form>
                </div>

            </div>

        </div>
    </div>
</div>

Tarifim.WebUI/Areas/Admin/Views/Food/List.cshtml
@model List<FoodListViewModel>

<div class="row">
    <div class="col-sm-8 container">
        <div class="card">
            <div class="card-header">
                <h3 class="card-title">Yemekler</h3>
            </div>
            <div class="card-body">
                <div class="table table-responsive table-responsive-sm">
                    <table class="table table-striped">
                        <thead>

                            <tr>
                                <th style="width:400px">Yemek Resim</th>
                                <th style="width:400px">Yemek Adı</th>
                                <th style="width:400px">Malzemeler</th>
                                <th style="width:400px">Tarif</th>
                                <th style="width:400px">Kategori</th>
                                <th style="width:400px">Düzenle</th>
                                <th style="width:400px">Sil</th>
                            </tr>

                        </thead>

                        <tbody>

                            @foreach (var food in Model)
                            {
                                <tr>
                                    <td>
                                        @if (string.IsNullOrWhiteSpace(food.FoodImage))
                                        {
                                            <img src="~/images/noPhoto.png" style="width:120px; height:120px;border-radius:50px;" />
                                        }
                                        else
                                        {
                                            <img src="~/images/foods/@food.FoodImage" alt="@food.Name" style="width:120px; height:120px;border-radius:50px;" />
                                        }
                                    </td>

                                    <td>@food.Name</td>
                                    <td>@food.Content</td>
                                    <td>@food.Description</td>
                                    <td>@food.CategoryName</td>
                                    <td>
                                        <a asp-area="Admin" asp-controller="Food" asp-action="UpdateFood" asp-route-id="@food.Id" class="btn btn-sm btn-primary"><i class="bi bi-pencil-square"></i> Güncelle</a>
                                    </td>
                                    <td>
                                        <a asp-area="Admin" asp-controller="Category" asp-action="DeleteFood" asp-route-id="@food.Id" class="btn btn-sm btn-danger"><i class="bi bi-trash3"></i> Sil</a>
                                    </td>

                                </tr>
                            }

                        </tbody>
                    </table>
                </div>
            </div>
            <div class="card-footer">
                <a asp-controller="Dashboard" asp-action="Index" class="btn btn-sm btn-primary mt-3" style="float:right">Geri Dön</a>
            </div>
        </div>
    </div>
</div>